/* =====================================================================
   Roastino (رستینو) for CoderSight  (SQL Server 2016+)
   Pages: /fa/ (home), /fa/menu, /fa/contact, plus nav, theme and settings.
   Generated by samples/roastino/gen_seed.py; edit that file, not this one.

   Needs the block variants and theme columns from the AddBrandTheme and
   AddThemeSurfaceAndHeadingFont migrations.

   Before running:
     1. Start the app once against the database so migrations and the
        default seed have run.
     2. Copy the files in samples/roastino/uploads into
        src/CoderSight.Web/wwwroot/uploads/.
     3. Fill in the variables below.
   Safe to re-run: it replaces the three Roastino pages and the nav menu.
   ===================================================================== */
SET NOCOUNT ON;
SET XACT_ABORT ON;

-- ---------- Fill these in ----------
DECLARE @Address        nvarchar(400)  = N'[نشانیِ کامل کافه]';
DECLARE @Hours          nvarchar(400)  = N'[روزهای کاری]: [ساعت باز و بسته شدن]';
DECLARE @Phone          nvarchar(100)  = N'[شماره‌ی تماس]';
DECLARE @Instagram      nvarchar(100)  = N'[آیدیِ اینستاگرام]';
DECLARE @InstagramUrl   nvarchar(400)  = NULL;   -- e.g. N'https://instagram.com/roastino'
DECLARE @RecipientEmail nvarchar(256)  = N'[ایمیلِ دریافتِ پیام‌ها]';
DECLARE @MapEmbedUrl    nvarchar(1000) = N'';    -- Google Maps > Share > Embed a map > the src="..." URL
DECLARE @SiteUrl        nvarchar(400)  = NULL;   -- e.g. N'https://roastino.ir'
DECLARE @ArchiveOtherPages bit = 1;              -- 1 = hide the CoderSight demo pages (Status = Archived; nothing is deleted)

-- JSON-escaped copies (spliced into block JSON), and double-escaped ones for blocks nested in Columns
DECLARE @AddressJson nvarchar(800) = STRING_ESCAPE(@Address, 'json');
DECLARE @HoursJson nvarchar(800) = STRING_ESCAPE(@Hours, 'json');
DECLARE @PhoneJson nvarchar(200) = STRING_ESCAPE(@Phone, 'json');
DECLARE @InstagramJson nvarchar(200) = STRING_ESCAPE(@Instagram, 'json');
DECLARE @RecipientEmailJson nvarchar(512) = STRING_ESCAPE(@RecipientEmail, 'json');
DECLARE @MapEmbedUrlJson nvarchar(2000) = STRING_ESCAPE(@MapEmbedUrl, 'json');
DECLARE @AddressJson2 nvarchar(1600) = STRING_ESCAPE(@AddressJson, 'json');
DECLARE @HoursJson2 nvarchar(1600) = STRING_ESCAPE(@HoursJson, 'json');
DECLARE @PhoneJson2 nvarchar(400) = STRING_ESCAPE(@PhoneJson, 'json');
DECLARE @InstagramJson2 nvarchar(400) = STRING_ESCAPE(@InstagramJson, 'json');
DECLARE @RecipientEmailJson2 nvarchar(1024) = STRING_ESCAPE(@RecipientEmailJson, 'json');
DECLARE @MapEmbedUrlJson2 nvarchar(4000) = STRING_ESCAPE(@MapEmbedUrlJson, 'json');

BEGIN TRANSACTION;

-- ---------- Site settings and brand theme ----------
UPDATE SiteSettings SET
    SiteName = N'رستینو',
    SiteUrl = COALESCE(@SiteUrl, SiteUrl),
    DefaultCulture = 'fa',
    SupportedCultures = 'fa',
    EnableMultilingual = 1,          -- keep on: the /fa/ URL segment is what makes pages right-to-left
    EnableUserRegistration = 0,      -- hides Sign In / Sign Up
    EnableBlogComments = 0,
    EnableUserBlogSubmissions = 0,
    LogoUrl = N'/uploads/roastino-logo.png',
    FaviconUrl = N'/uploads/roastino-favicon.png',
    OgImageUrl = N'/uploads/roastino-og-image.png',
    DefaultMetaDescription = N'رستینو، کافه‌بار و فروشگاه قهوه.',
    FooterText = N'© ۱۴۰۵ رستینو · کافه‌بار و فروشگاه قهوه',
    SocialInstagram = @InstagramUrl,
    SiteBackgroundColor = '#FBF4EA',
    -- Empty NavStyles/FooterStyles make the navbar and footer use the colours below.
    NavStyles = N'', FooterStyles = N'',
    NavBackgroundColor = '#FBF4EA', NavTextColor = '#2B1A14', NavBorderColor = '#E6D5BF',
    NavLogoTextColor = '#2B1A14', NavHoverColor = '#C8161F',
    NavHeight = '4.5rem', NavLogoHeight = '3rem', NavLogoFontSize = '1.6rem',
    FooterBackgroundColor = '#2B1A14', FooterTextColor = '#E6D5BF', FooterHeadingColor = '#FFFFFF',
    FooterLinkHoverColor = '#FFFFFF', FooterBorderColor = '#47322A',
    ThemePrimaryColor = '#C8161F', ThemePrimaryHoverColor = '#A50F18', ThemeOnPrimaryColor = '#FFFFFF',
    ThemeInkColor = '#2B1A14', ThemeDarkColor = '#8A5A3B', ThemeMutedColor = '#6B5448',
    ThemeSurfaceColor = '#FFFDF9', ThemeBorderColor = '#E6D5BF', ThemeRadius = '1.25rem',
    ThemeFontFamily = 'Vazirmatn', ThemeHeadingFontFamily = 'Noto Naskh Arabic';

-- ---------- Navigation ----------
DELETE FROM NavMenuItems WHERE ParentId IS NOT NULL;
DELETE FROM NavMenuItems;
INSERT INTO NavMenuItems (Id, ParentId, Label, LabelFa, Url, OpenInNewTab, SortOrder, IsVisible) VALUES
    (NEWID(), NULL, N'Home',    N'خانه',       N'',        0, 0, 1),
    (NEWID(), NULL, N'Menu',    N'منوی قهوه',  N'menu',    0, 1, 1),
    (NEWID(), NULL, N'Contact', N'تماس با ما', N'contact', 0, 2, 1);

-- ---------- Media library ----------
DELETE FROM Media WHERE Url LIKE N'/uploads/roastino-%';
INSERT INTO Media (Id, FileName, Url, ContentType, SizeBytes, AltText, UploadedAt) VALUES
    (NEWID(), N'roastino-logo.png', N'/uploads/roastino-logo.png', 'image/png', 33920, N'لوگوی رستینو', SYSUTCDATETIME()),
    (NEWID(), N'roastino-favicon.png', N'/uploads/roastino-favicon.png', 'image/png', 12261, N'آیکونِ رستینو', SYSUTCDATETIME()),
    (NEWID(), N'roastino-og-image.png', N'/uploads/roastino-og-image.png', 'image/png', 61054, N'رستینو', SYSUTCDATETIME()),
    (NEWID(), N'roastino-gallery-bar.jpg', N'/uploads/roastino-gallery-bar.jpg', 'image/jpeg', 30351, N'بارِ قهوه‌ی رستینو', SYSUTCDATETIME()),
    (NEWID(), N'roastino-gallery-beans.jpg', N'/uploads/roastino-gallery-beans.jpg', 'image/jpeg', 29718, N'قفسه‌ی دانه‌های قهوه', SYSUTCDATETIME()),
    (NEWID(), N'roastino-gallery-space.jpg', N'/uploads/roastino-gallery-space.jpg', 'image/jpeg', 30351, N'فضای کافه', SYSUTCDATETIME()),
    (NEWID(), N'roastino-beans-espresso.jpg', N'/uploads/roastino-beans-espresso.jpg', 'image/jpeg', 25318, N'ترکیبِ اسپرسو', SYSUTCDATETIME()),
    (NEWID(), N'roastino-beans-single-origin.jpg', N'/uploads/roastino-beans-single-origin.jpg', 'image/jpeg', 25318, N'عربیکای تک‌خاستگاه', SYSUTCDATETIME()),
    (NEWID(), N'roastino-beans-turkish.jpg', N'/uploads/roastino-beans-turkish.jpg', 'image/jpeg', 25318, N'قهوه‌ی ترک', SYSUTCDATETIME());

-- ---------- Pages ----------
DELETE FROM Pages WHERE Culture = 'fa' AND Slug IN (N'', N'menu', N'contact');   -- their blocks cascade

IF @ArchiveOtherPages = 1
    UPDATE Pages SET Status = 'Archived', UpdatedAt = SYSUTCDATETIME()
    WHERE NOT (Culture = 'fa' AND Slug IN (N'', N'menu', N'contact'));

DECLARE @HomeId uniqueidentifier = NEWID(), @MenuId uniqueidentifier = NEWID(), @ContactId uniqueidentifier = NEWID();

-- خانه  (/fa/)
INSERT INTO Pages (Id, Title, Slug, Status, MetaTitle, MetaDescription, Culture, LocalizationGroupId, CreatedAt, UpdatedAt, PublishedAt)
VALUES (@HomeId, N'خانه', N'', 'Published', N'رستینو | کافه‌بار و فروشگاه قهوه', N'رستینو، کافه‌بار و فروشگاه قهوه. قهوه را پشتِ بار برایتان دم می‌کنیم و دانه‌ی قهوه را برای خانه می‌فروشیم.', 'fa', NULL, SYSUTCDATETIME(), SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO PageBlocks (Id, PageId, BlockType, SortOrder, Data, Styles) VALUES
    (NEWID(), @HomeId, N'Hero', 0,
     N'{"layout":"split","eyebrow":"کافه‌بار و فروشگاه قهوه","title":"یک فنجانِ خوب،\nهمین‌جا یا در خانه","subtitle":"در رستینو قهوه را پشتِ بار و جلوی چشمتان دم می‌کنیم و دانه‌ی قهوه را هم برای خانه می‌فروشیم. بیایید و بنشینید، یا قهوه‌تان را با خودتان ببرید.","buttonText":"سری به ما بزنید","buttonLink":"/fa/contact","imageUrl":"/uploads/roastino-logo.png"}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @HomeId, N'CardGrid', 1,
     N'{"sectionTitle":"دو کار، با یک علاقه","columns":2,"layout":"stacked","cards":[{"icon":"coffee","title":"کافه‌بار","description":"اسپرسو و قهوه‌ی دمی، پشتِ بار و جلوی چشم شما. چند صندلی برای نشستن و نوشیدنِ یک فنجان با حوصله.","linkText":"منوی قهوه","linkUrl":"/fa/menu"},{"icon":"shopping-bag","title":"فروشِ قهوه","description":"دانه‌ی قهوه برای خانه و محلِ کار. اگر نمی‌دانید کدام را بردارید، در انتخاب کمکتان می‌کنیم.","linkText":"دانه‌ها","linkUrl":"/fa/menu"}]}',
     N'{"backgroundColor":"#FFFDF9","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0","borderColor":"#E6D5BF","borderWidth":"1px 0"}'),
    (NEWID(), @HomeId, N'Heading', 2,
     N'{"text":"داستانِ یک کافه‌ی کوچک","level":"h2","alignment":"center"}',
     N'{"backgroundColor":"transparent","paddingTop":"2rem","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @HomeId, N'RichText', 3,
     N'{"content":"<p>رستینو با یک فکرِ ساده شروع شد: قهوه‌ی خوب باید در دسترس باشد، چه در فنجانی که پشتِ بار برایتان دم می‌کنیم، چه در کیسه‌ای که با خودتان به خانه می‌برید.</p><p>جا کم است، اما برای یک فنجانِ خوب و یک گفت‌وگوی کوتاه، همیشه جا هست.</p>"}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0","textAlign":"center","fontSize":"1.125rem"}'),
    (NEWID(), @HomeId, N'ImageGallery', 4,
     N'{"layout":"grid","columns":3,"images":[{"imageUrl":"/uploads/roastino-gallery-bar.jpg","altText":"بارِ قهوه‌ی رستینو"},{"imageUrl":"/uploads/roastino-gallery-beans.jpg","altText":"قفسه‌ی دانه‌های قهوه"},{"imageUrl":"/uploads/roastino-gallery-space.jpg","altText":"فضای کافه"}]}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"2rem","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @HomeId, N'CardGrid', 5,
     REPLACE(REPLACE(REPLACE(N'{"sectionTitle":"سری به ما بزنید","columns":3,"layout":"stacked","cards":[{"icon":"map-pin","title":"نشانی","description":"{{ADDRESS}}","linkText":"مسیریابی","linkUrl":"/fa/contact"},{"icon":"clock","title":"ساعتِ کار","description":"{{HOURS}}"},{"icon":"phone","title":"تماس","description":"{{PHONE}}","linkText":"صفحه‌ی تماس با ما","linkUrl":"/fa/contact"}]}', N'{{ADDRESS}}', @AddressJson), N'{{HOURS}}', @HoursJson), N'{{PHONE}}', @PhoneJson),
     N'{"backgroundColor":"#F3E6D3","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @HomeId, N'Newsletter', 6,
     N'{"style":"brand","title":"قهوه‌ی تازه که رسید، خبرتان می‌کنیم","description":"ماهی یکی‌دو ایمیل؛ فقط دانه‌های تازه و خبرهای کافه.","buttonText":"عضویت","placeholder":"ایمیلِ شما"}',
     N'{"backgroundColor":"transparent","paddingTop":"2rem","paddingBottom":"2rem","paddingLeft":"0","paddingRight":"0"}');

-- منوی قهوه  (/fa/menu)
INSERT INTO Pages (Id, Title, Slug, Status, MetaTitle, MetaDescription, Culture, LocalizationGroupId, CreatedAt, UpdatedAt, PublishedAt)
VALUES (@MenuId, N'منوی قهوه', N'menu', 'Published', N'منوی قهوه | رستینو', N'منوی نوشیدنی‌های بارِ رستینو و دانه‌های قهوه برای خانه.', 'fa', NULL, SYSUTCDATETIME(), SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO PageBlocks (Id, PageId, BlockType, SortOrder, Data, Styles) VALUES
    (NEWID(), @MenuId, N'Heading', 0,
     N'{"text":"منوی قهوه","subtitle":"نوشیدنی‌هایی که پشتِ بار آماده می‌کنیم و دانه‌هایی که برای خانه می‌فروشیم.","level":"h1","alignment":"center"}',
     N'{"backgroundColor":"#F3E6D3","paddingTop":"2rem","paddingBottom":"2rem","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @MenuId, N'ProductShowcase', 1,
     N'{"sectionTitle":"بر پایه‌ی اسپرسو","sectionSubtitle":"تک یا دوبل، با شیر یا بدون شیر","layout":"list","columns":2,"animation":"fade-up","products":[{"title":"اسپرسو","description":"یک یا دو شات، غلیظ و پرکرما.","badge":"","price":""},{"title":"آمریکانو","description":"اسپرسو با آبِ داغ؛ سبک‌تر و بلندتر.","badge":"","price":""},{"title":"کاپوچینو","description":"اسپرسو، شیرِ داغ و فومِ پرحجم.","badge":"","price":""},{"title":"لاته","description":"اسپرسو با شیرِ داغِ بیشتر و لایه‌ی نازکِ فوم.","badge":"","price":""},{"title":"فلت‌وایت","description":"دو شات با شیرِ مخملی؛ قهوه پررنگ‌تر از لاته.","badge":"پیشنهادِ باریستا","price":""},{"title":"کورتادو","description":"اسپرسو و کمی شیر؛ کوچک و پرقدرت.","badge":"","price":""},{"title":"ماکیاتو","description":"اسپرسو با یک قاشق فومِ شیر.","badge":"","price":""},{"title":"موکا","description":"اسپرسو، شکلاتِ داغ و شیر.","badge":"","price":""}]}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @MenuId, N'ProductShowcase', 2,
     N'{"sectionTitle":"قهوه‌ی دمی","sectionSubtitle":"دم‌آوریِ دستی، با دانه‌ای که خودتان انتخاب می‌کنید","layout":"list","columns":2,"animation":"fade-up","products":[{"title":"V60","description":"روشن و شفاف؛ مناسبِ دانه‌های میوه‌ای.","badge":"","price":""},{"title":"کمکس","description":"برای دو نفر، با طعمی تمیز و ملایم.","badge":"","price":""},{"title":"فرنچ‌پرس","description":"پرتن و غلیظ، با بافتی سنگین‌تر.","badge":"","price":""},{"title":"ایروپرس","description":"سریع و متعادل، بینِ اسپرسو و دمی.","badge":"","price":""},{"title":"قهوه‌ی ترک","description":"آسیابِ خیلی نرم، روی حرارتِ ملایم.","badge":"","price":""}]}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @MenuId, N'ProductShowcase', 3,
     N'{"sectionTitle":"نوشیدنی‌های سرد","sectionSubtitle":"برای روزهای گرم، و هر وقت که دلتان بخواهد","layout":"list","columns":2,"animation":"fade-up","products":[{"title":"آیس‌آمریکانو","description":"دو شات اسپرسو روی آبِ سرد و یخ.","badge":"","price":""},{"title":"آیس‌لاته","description":"اسپرسو روی شیرِ سرد و یخ.","badge":"","price":""},{"title":"کلدبرو","description":"قهوه‌ای که ساعت‌ها در آبِ سرد دم کشیده؛ نرم و کم‌تلخی.","badge":"","price":""},{"title":"اسپرسو تونیک","description":"اسپرسو روی تونیک و یخ.","badge":"","price":""},{"title":"آفوگاتو","description":"یک اسکوپ بستنیِ وانیلی زیرِ شاتِ داغِ اسپرسو.","badge":"","price":""}]}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @MenuId, N'ProductShowcase', 4,
     N'{"sectionTitle":"دانه‌ی قهوه برای خانه","sectionSubtitle":"قهوه‌ای را که پشتِ بار دوست داشتید، به خانه ببرید","layout":"cards","columns":3,"animation":"fade-up","products":[{"title":"ترکیبِ اسپرسو","description":"برای دستگاهِ اسپرسو و موکاپات.","imageUrl":"/uploads/roastino-beans-espresso.jpg","price":""},{"title":"عربیکای تک‌خاستگاه","description":"برای V60 و کمکس.","imageUrl":"/uploads/roastino-beans-single-origin.jpg","price":""},{"title":"قهوه‌ی ترک","description":"آسیابِ خیلی نرم، آماده‌ی دم.","imageUrl":"/uploads/roastino-beans-turkish.jpg","price":""}]}',
     N'{"backgroundColor":"#F3E6D3","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0","marginTop":"3rem"}'),
    (NEWID(), @MenuId, N'RichText', 5,
     N'{"content":"<p>قیمت‌ها به تومان است. برای موجودیِ دانه‌ها و نوشیدنیِ روز، از باریستا بپرسید.</p>"}',
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0","textAlign":"center"}');

-- تماس با ما  (/fa/contact)
INSERT INTO Pages (Id, Title, Slug, Status, MetaTitle, MetaDescription, Culture, LocalizationGroupId, CreatedAt, UpdatedAt, PublishedAt)
VALUES (@ContactId, N'تماس با ما', N'contact', 'Published', N'تماس با ما | رستینو', N'نشانی، ساعتِ کار و راه‌های تماس با رستینو.', 'fa', NULL, SYSUTCDATETIME(), SYSUTCDATETIME(), SYSUTCDATETIME());
INSERT INTO PageBlocks (Id, PageId, BlockType, SortOrder, Data, Styles) VALUES
    (NEWID(), @ContactId, N'Heading', 0,
     N'{"text":"تماس با ما","subtitle":"سؤالی درباره‌ی قهوه دارید یا می‌خواهید دانه‌ای را برایتان کنار بگذاریم؟ پیام بدهید، یا بهتر از آن، سری به کافه بزنید.","level":"h1","alignment":"center"}',
     N'{"backgroundColor":"#F3E6D3","paddingTop":"2rem","paddingBottom":"2rem","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @ContactId, N'Columns', 1,
     REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(N'{"columnCount":2,"gap":"2rem","columns":[{"width":"38%","blocks":[{"blockType":"CardGrid","data":"{\"columns\":1,\"layout\":\"inline\",\"cards\":[{\"icon\":\"map-pin\",\"title\":\"نشانی\",\"description\":\"{{N_ADDRESS}}\"},{\"icon\":\"clock\",\"title\":\"ساعتِ کار\",\"description\":\"{{N_HOURS}}\"},{\"icon\":\"phone\",\"title\":\"تلفن\",\"description\":\"{{N_PHONE}}\"},{\"icon\":\"brand-instagram\",\"title\":\"اینستاگرام\",\"description\":\"{{N_INSTAGRAM}}\"}]}"}]},{"width":"60%","blocks":[{"blockType":"ContactForm","data":"{\"title\":\"پیام بفرستید\",\"description\":\"پیامتان را بنویسید؛ به‌زودی پاسخ می‌دهیم.\",\"recipientEmail\":\"{{N_RECIPIENT_EMAIL}}\",\"submitButtonText\":\"ارسالِ پیام\",\"fields\":[{\"label\":\"نام\",\"name\":\"name\",\"type\":\"text\",\"required\":true,\"placeholder\":\"نامِ شما\"},{\"label\":\"ایمیل\",\"name\":\"email\",\"type\":\"email\",\"required\":true,\"placeholder\":\"email@example.com\"},{\"label\":\"موضوع\",\"name\":\"subject\",\"type\":\"text\",\"required\":false,\"placeholder\":\"مثلاً خریدِ دانه‌ی قهوه\"},{\"label\":\"پیام\",\"name\":\"message\",\"type\":\"textarea\",\"required\":true,\"placeholder\":\"پیامتان را بنویسید\"}]}"}]}]}', N'{{N_ADDRESS}}', @AddressJson2), N'{{N_HOURS}}', @HoursJson2), N'{{N_PHONE}}', @PhoneJson2), N'{{N_INSTAGRAM}}', @InstagramJson2), N'{{N_RECIPIENT_EMAIL}}', @RecipientEmailJson2),
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"0","paddingLeft":"0","paddingRight":"0"}'),
    (NEWID(), @ContactId, N'MapEmbed', 2,
     REPLACE(N'{"embedUrl":"{{MAP_EMBED_URL}}","height":420}', N'{{MAP_EMBED_URL}}', @MapEmbedUrlJson),
     N'{"backgroundColor":"transparent","paddingTop":"0","paddingBottom":"3rem","paddingLeft":"0","paddingRight":"0"}');

COMMIT TRANSACTION;

SELECT p.Slug, p.Title, p.Status, COUNT(b.Id) AS Blocks
FROM Pages p LEFT JOIN PageBlocks b ON b.PageId = p.Id
WHERE p.Culture = 'fa' AND p.Slug IN (N'', N'menu', N'contact')
GROUP BY p.Slug, p.Title, p.Status;
